global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'node_exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9100']  
  - job_name: 'ceph'
    honor_labels: true
    file_sd_configs:
     - files:
       - ceph_targets.yml
  - job_name: 'node'
    honor_labels: true
    file_sd_configs:
     - files:
       - node_targets.yml
